[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sbe-ctd-proc"
version = "0.1"
authors = [
    {name = "Arlo White", email = "a.white@aims.gov.au"}
]
readme = "README.md"

requires-python = ">= 3.8"
dependencies = [
    "customtkinter",
    "pandas",
    "SQLAlchemy"
]

[project.scripts]
sbe-ctd-proc-cli = "sbe_ctd_proc:start_gui"

[project.gui-scripts]
sbe-ctd-proc = "sbe_ctd_proc:start_gui"
